name: Matt Kohn
favicon: null
layout_spectrum: 0.41388
typography_spectrum: 0.31708239763975143
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.625
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
