name: Matt Kohn
favicon: null
layout_spectrum: 0.4389172832015902
typography_spectrum: 0.31708239763975143
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.625
  lightness: 0.045452648075297475
  saturation: 0.3603112327400595
  rhythmicContrast: 0.8803021972998977
purpose: []
