name: Matt Kohn
favicon: null
layout_spectrum: 0.28032
typography_spectrum: 0.65264
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e789e9'
    - '#75383d'
    - '#ac8d7b'
    - '#dd1c5f'
    - '#dfd4b8'
  brandStrength: 0.625
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
